#!/bin/bash
model_server_timeout=1200
model_server_workers=1

# Start nginx
nginx

# Start Gunicorn (which starts the Flask app)
# Using one worker here because the model is heavy (GPU memory constraints)
exec gunicorn --timeout ${model_server_timeout} \
              --workers ${model_server_workers} \
              --bind 0.0.0.0:8080 \
              app:app
